// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq4V61aEk6F-5u8TqDbD17XxTBur2i7w4',
    appId: '1:250095454000:web:df8741c9eea015504baaf5',
    messagingSenderId: '250095454000',
    projectId: 'flutter-client-holder',
    authDomain: 'flutter-client-holder.firebaseapp.com',
    storageBucket: 'flutter-client-holder.appspot.com',
    measurementId: 'G-KK6ZKFHLBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnhIJG0LmTiHXiPyeMlJK4qu_zN3Q47Lc',
    appId: '1:250095454000:android:37b11a9f773cecdd4baaf5',
    messagingSenderId: '250095454000',
    projectId: 'flutter-client-holder',
    storageBucket: 'flutter-client-holder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNcO6rwkFWajSpPHAKRb7l6Rr7ZQAJB58',
    appId: '1:250095454000:ios:898536dedc145af04baaf5',
    messagingSenderId: '250095454000',
    projectId: 'flutter-client-holder',
    storageBucket: 'flutter-client-holder.appspot.com',
    iosClientId: '250095454000-iijeq3lnfudf9650aavoce1qvgaar6d2.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientHolder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNcO6rwkFWajSpPHAKRb7l6Rr7ZQAJB58',
    appId: '1:250095454000:ios:898536dedc145af04baaf5',
    messagingSenderId: '250095454000',
    projectId: 'flutter-client-holder',
    storageBucket: 'flutter-client-holder.appspot.com',
    iosClientId: '250095454000-iijeq3lnfudf9650aavoce1qvgaar6d2.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientHolder',
  );
}
